version: "3.5"
services:
  jenkins:
    build: .
    image: oa/jenkins-docker:latest
    ports:
      - "8080:8080"
      - "5000:5000"
    networks:
      - maven-demo-net
    links:
      - "nexus:nexus"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  nexus:
    image: sonatype/nexus3
    networks:
          - maven-demo-net
    ports:
      - 8081:8081
    volumes:
      - ./nexus-data:/nexus-data
networks:
  maven-demo-net:
    name: maven-demo-net